name = "woodwire-worker"
main = "index.js"
compatibility_date = "2026-06-30"

workers_dev = false
routes = [
  { pattern = "${CLOUDFLARE_ROUTE_PATTERN}", zone_name = "${CLOUDFLARE_ZONE_NAME}" }
]

[observability.logs]
enabled = true
